"""store itinerary plans

Revision ID: 5ea56bc345bf
Revises: 9a3ef6a53733
Create Date: 2026-05-01 23:19:46.046233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea56bc345bf'
down_revision: Union[str, Sequence[str], None] = '9a3ef6a53733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('original_prompt', sa.Text(), nullable=False),
    sa.Column('extracted_request', sa.JSON(), nullable=False),
    sa.Column('active_context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_requests_user_id'), 'trip_requests', ['user_id'], unique=False)
    op.create_table('itinerary_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trip_request_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('itinerary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_request_id'], ['trip_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_plans_trip_request_id'), 'itinerary_plans', ['trip_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_plans_trip_request_id'), table_name='itinerary_plans')
    op.drop_table('itinerary_plans')
    op.drop_index(op.f('ix_trip_requests_user_id'), table_name='trip_requests')
    op.drop_table('trip_requests')
    # ### end Alembic commands ###
