"""create preference memory tables

Revision ID: 9a3ef6a53733
Revises: 
Create Date: 2026-04-30 20:16:06.853673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3ef6a53733'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_slug'), 'users', ['slug'], unique=True)
    op.create_table('preference_updates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('candidate', sa.JSON(), nullable=False),
    sa.Column('applied_patch', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preference_updates_user_id'), 'preference_updates', ['user_id'], unique=False)
    op.create_table('user_preference_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pace', sa.String(length=32), nullable=True),
    sa.Column('budget_level', sa.String(length=32), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('food_preferences', sa.JSON(), nullable=False),
    sa.Column('dislikes', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preference_profiles_user_id'), 'user_preference_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preference_profiles_user_id'), table_name='user_preference_profiles')
    op.drop_table('user_preference_profiles')
    op.drop_index(op.f('ix_preference_updates_user_id'), table_name='preference_updates')
    op.drop_table('preference_updates')
    op.drop_index(op.f('ix_users_slug'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
